// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQFTWN8VWuKsxOIKT77iE2y1va_U_ZINg',
    appId: '1:690968716028:web:26e8a300f325897e48ad79',
    messagingSenderId: '690968716028',
    projectId: 'vform-d05b7',
    authDomain: 'vform-d05b7.firebaseapp.com',
    storageBucket: 'vform-d05b7.appspot.com',
    measurementId: 'G-N2E48NG95T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuk-gaYABJfP9XmD3e9caZApDiDcSXZwE',
    appId: '1:690968716028:android:433a39799ceeabc948ad79',
    messagingSenderId: '690968716028',
    projectId: 'vform-d05b7',
    storageBucket: 'vform-d05b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5nQ1ZVO6muoQ-tilIXh3gcxuVi3gdvrY',
    appId: '1:690968716028:ios:70b74f6242e261d348ad79',
    messagingSenderId: '690968716028',
    projectId: 'vform-d05b7',
    storageBucket: 'vform-d05b7.appspot.com',
    androidClientId: '690968716028-j7oeg1q15j4b2gs77lbumtl6gkgkr0jd.apps.googleusercontent.com',
    iosClientId: '690968716028-ktgag8gak085soana1m36529l7v97vel.apps.googleusercontent.com',
    iosBundleId: 'com.example.vform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5nQ1ZVO6muoQ-tilIXh3gcxuVi3gdvrY',
    appId: '1:690968716028:ios:70b74f6242e261d348ad79',
    messagingSenderId: '690968716028',
    projectId: 'vform-d05b7',
    storageBucket: 'vform-d05b7.appspot.com',
    androidClientId: '690968716028-j7oeg1q15j4b2gs77lbumtl6gkgkr0jd.apps.googleusercontent.com',
    iosClientId: '690968716028-ktgag8gak085soana1m36529l7v97vel.apps.googleusercontent.com',
    iosBundleId: 'com.example.vform',
  );
}
